/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cs572.assignments.Project2.view;

import java.awt.BorderLayout;
import java.io.IOException;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

import com.cs572.assignments.Project2.model.Population;
import com.cs572.assignments.Project2.utility.GraphWriter;

/**
 *
 * @author prajjwol
 */
public class ExpressionTree extends javax.swing.JPanel {
    /**
     * Creates new form LineChartPanel
     */
    public ExpressionTree() {
        initComponents();
    }
    
    public JPanel getTree(Population popn){
        JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout());
        panel1.removeAll();
        writeGraphFile(popn);
        ImageIcon pic = new ImageIcon("output.png");
        panel1.add(new JLabel(pic),BorderLayout.CENTER);
        return panel1;
    }
    
    
    
    private void writeGraphFile(Population popn){
    		GraphWriter.writeContent(popn.getBestExprGraph());
                //File file= new File("output.png");
//                if(file.exists())
//                {
//                    file.delete();
//                }
		String command = "dot -Tpng input.gv -o output.png";
		try {
			Runtime.getRuntime().exec(command);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

}
